# Generated by Django 5.1.5 on 2025-02-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics/'),
        ),
    ]
