# Generated by Django 5.1.5 on 2025-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_height_customuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
