# Generated by Django 5.1.5 on 2025-03-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('DM', 'DM'), ('MCH', 'MCH'), ('Diploma', 'Diploma'), ('Fellowship', 'Fellowship'), ('DNB', 'DNB'), ('PhD', 'PhD'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
