# Generated by Django 5.1.5 on 2025-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, help_text='Enter multiple degrees separated by commas (e.g., MBBS, MD, DM)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Endocrinologist', 'Endocrinologist'), ('Pulmonologist', 'Pulmonologist'), ('Neurologist', 'Neurologist'), ('Hepatologist', 'Hepatologist'), ('Oncologist', 'Oncologist'), ('Nephrologist', 'Nephrologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Rheumatologist', 'Rheumatologist'), ('Allergist/Immunologist', 'Allergist/Immunologist'), ('Pulmonary Critical Care', 'Pulmonary Critical Care'), ('Geriatrician', 'Geriatrician'), ('Endoscopic Surgeon', 'Endoscopic Surgeon'), ('Internal Medicine', 'Internal Medicine'), ('Psychiatrist', 'Psychiatrist'), ('Pediatrician', 'Pediatrician'), ('Thoracic Surgeon', 'Thoracic Surgeon'), ('Vascular Surgeon', 'Vascular Surgeon'), ('Dermatologist', 'Dermatologist'), ('ENT Specialist', 'ENT Specialist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Sports Medicine Specialist', 'Sports Medicine Specialist'), ('Community Medicine Specialist', 'Community Medicine Specialist')], max_length=100, null=True),
        ),
    ]
