# Generated by Django 5.1.5 on 2025-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_about_customuser_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
