# Generated by Django 5.1.5 on 2025-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_office_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='office_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
