# Generated by Django 5.1.5 on 2025-01-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('cholesterol_level', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('smoking_status', models.CharField(blank=True, choices=[('non_smoker', 'Non-Smoker'), ('current_smoker', 'Current Smoker'), ('ex_smoker', 'Ex-Smoker')], max_length=50, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'None'), ('occasional', 'Occasional'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=50, null=True)),
                ('physical_activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('high', 'High')], max_length=50, null=True)),
                ('family_history_diabetes', models.BooleanField(default=False)),
                ('family_history_heart_disease', models.BooleanField(default=False)),
                ('family_history_cancer', models.BooleanField(default=False)),
                ('existing_conditions', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
