# Generated by Django 5.1.5 on 2025-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='family_history_cancer',
            new_name='family_history_bloodcancer',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='family_history_asthma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='family_history_liver_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='family_history_parkinsons',
            field=models.BooleanField(default=False),
        ),
    ]
