# Generated by Django 5.1.5 on 2025-02-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_family_history_cancer_medicalhistory_family_history_bloodcancer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='family_history_bloodcancer',
            new_name='family_history_lungcancer',
        ),
    ]
