# Generated by Django 5.1.1 on 2025-02-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_family_history_bloodcancer_medicalhistory_family_history_lungcancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='cholesterol_hdl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='cholesterol_ldl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='cholesterol_triglycerides',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diastolic_bp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hba1c_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='systolic_bp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
