# Generated by Django 5.1.5 on 2025-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_medicalhistory_blood_sugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='blood_pressure',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
